blank_issues_enabled: false
contact_links:
  - name: 💬 Community Q&A
    url: https://github.com/tbowman01/Soc-2-compliance/discussions
    about: Ask questions, propose ideas, or get help in the Discussions tab
